sudo: false

language: python

cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.6"

notifications:
  email: false

install:
  - pip install -r requirements.txt

script:
  - python setup.py install
  - nosetests test/unit
